create procedure gendelete
@tab varchar(128)
AS
BEGIN
    DECLARE @SALIDA TABLE (Texto VARCHAR(2048))
    --INSERT INTO @SALIDA VALUES ('IF OBJECT_ID(' + CHAR(39) + 'D_' + @tab + CHAR(39) + ',' + CHAR(39) + 'P' + CHAR(39) + ') IS NOT NULL')
    --INSERT INTO @SALIDA VALUES ('    DROP PROCEDURE D_' + @tab)
    --INSERT INTO @SALIDA VALUES ('GO')
    INSERT INTO @SALIDA VALUES ('CREATE PROCEDURE D_' + @tab)
    INSERT INTO @SALIDA VALUES ('@ID INTEGER')
    INSERT INTO @SALIDA VALUES ('AS')
    INSERT INTO @SALIDA VALUES ('BEGIN')
    INSERT INTO @SALIDA VALUES ('  BEGIN TRY')
    INSERT INTO @SALIDA VALUES ('    DELETE FROM ' + @tab + ' WHERE ID = @ID')
    INSERT INTO @SALIDA VALUES ('  END TRY')
    INSERT INTO @SALIDA VALUES ('  BEGIN CATCH')
    INSERT INTO @SALIDA VALUES ('     EXECUTE GetErrorInfo_sp')
    INSERT INTO @SALIDA VALUES ('  END CATCH'    )
    INSERT INTO @SALIDA VALUES ('END')
    --INSERT INTO @SALIDA VALUES ('GO')
    SELECT Texto FROM @SALIDA
END;
