---------------------------------------
-- TABLA: INSTITUCION   ----------------
---------------------------------------
IF OBJECT_ID('D_INSTITUCION','P') IS NOT NULL
    DROP PROCEDURE D_INSTITUCION
GO
CREATE PROCEDURE D_INSTITUCION
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM INSTITUCION WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
IF OBJECT_ID('U_INSTITUCION','P') IS NOT NULL
    DROP PROCEDURE I_INSTITUCION
GO

CREATE PROCEDURE I_INSTITUCION
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(512)
   ,@IDNACIONAL VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    INSERT INTO INSTITUCION
    (NOMBRE ,IDNACIONAL)
    VALUES
    (@NOMBRE ,@IDNACIONAL)
SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
IF OBJECT_ID('U_INSTITUCION','P') IS NOT NULL
    DROP PROCEDURE U_INSTITUCION
GO

CREATE PROCEDURE U_INSTITUCION
    @ID INT
   ,@NOMBRE VARCHAR(512)
   ,@IDNACIONAL VARCHAR(128)
AS
BEGIN
  BEGIN TRY
    UPDATE INSTITUCION SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,IDNACIONAL = ISNULL(@IDNACIONAL, IDNACIONAL)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
---------------------------------------
-- TABLA: ORIENTACION   ----------------
---------------------------------------
IF OBJECT_ID('D_ORIENTACION','P') IS NOT NULL
    DROP PROCEDURE D_ORIENTACION
GO
CREATE PROCEDURE D_ORIENTACION
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM ORIENTACION WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
IF OBJECT_ID('U_ORIENTACION','P') IS NOT NULL
    DROP PROCEDURE I_ORIENTACION
GO

CREATE PROCEDURE I_ORIENTACION
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(512)
AS
BEGIN
  BEGIN TRY
    INSERT INTO ORIENTACION
    (NOMBRE)
    VALUES
    (@NOMBRE)
SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
IF OBJECT_ID('U_ORIENTACION','P') IS NOT NULL
    DROP PROCEDURE U_ORIENTACION
GO

CREATE PROCEDURE U_ORIENTACION
    @ID INT
   ,@NOMBRE VARCHAR(512)
AS
BEGIN
  BEGIN TRY
    UPDATE ORIENTACION SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
---------------------------------------
-- TABLA: NIVEL   ----------------
---------------------------------------
IF OBJECT_ID('D_NIVEL','P') IS NOT NULL
    DROP PROCEDURE D_NIVEL
GO
CREATE PROCEDURE D_NIVEL
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM NIVEL WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
IF OBJECT_ID('U_NIVEL','P') IS NOT NULL
    DROP PROCEDURE I_NIVEL
GO

CREATE PROCEDURE I_NIVEL
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(512)
AS
BEGIN
  BEGIN TRY
    INSERT INTO NIVEL
    (NOMBRE)
    VALUES
    (@NOMBRE)
SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
IF OBJECT_ID('U_NIVEL','P') IS NOT NULL
    DROP PROCEDURE U_NIVEL
GO

CREATE PROCEDURE U_NIVEL
    @ID INT
   ,@NOMBRE VARCHAR(512)
AS
BEGIN
  BEGIN TRY
    UPDATE NIVEL SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
---------------------------------------
-- TABLA: MATERIA   ----------------
---------------------------------------
IF OBJECT_ID('D_MATERIA','P') IS NOT NULL
    DROP PROCEDURE D_MATERIA
GO
CREATE PROCEDURE D_MATERIA
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM MATERIA WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
IF OBJECT_ID('U_MATERIA','P') IS NOT NULL
    DROP PROCEDURE I_MATERIA
GO

CREATE PROCEDURE I_MATERIA
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(512)
AS
BEGIN
  BEGIN TRY
    INSERT INTO MATERIA
    (NOMBRE)
    VALUES
    (@NOMBRE)
SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
IF OBJECT_ID('U_MATERIA','P') IS NOT NULL
    DROP PROCEDURE U_MATERIA
GO

CREATE PROCEDURE U_MATERIA
    @ID INT
   ,@NOMBRE VARCHAR(512)
AS
BEGIN
  BEGIN TRY
    UPDATE MATERIA SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
---------------------------------------
-- TABLA: PERSONA   ----------------
---------------------------------------
IF OBJECT_ID('D_PERSONA','P') IS NOT NULL
    DROP PROCEDURE D_PERSONA
GO
CREATE PROCEDURE D_PERSONA
@ID INTEGER
AS
BEGIN
  BEGIN TRY
    DELETE FROM PERSONA WHERE ID = @ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
IF OBJECT_ID('U_PERSONA','P') IS NOT NULL
    DROP PROCEDURE I_PERSONA
GO

CREATE PROCEDURE I_PERSONA
    @ID INT OUTPUT
   ,@NOMBRE VARCHAR(128)
   ,@APELLIDO VARCHAR(128)
   ,@DNI VARCHAR(32)
   ,@FNACTO DATETIME
   ,@GENERO CHAR(1)
   ,@DOMICILIO VARCHAR(1024)
AS
BEGIN
  BEGIN TRY
    INSERT INTO PERSONA
    (NOMBRE ,APELLIDO ,DNI ,FNACTO ,GENERO ,DOMICILIO)
    VALUES
    (@NOMBRE ,@APELLIDO ,@DNI ,@FNACTO ,@GENERO ,@DOMICILIO)
SET @ID = @@IDENTITY
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
IF OBJECT_ID('U_PERSONA','P') IS NOT NULL
    DROP PROCEDURE U_PERSONA
GO

CREATE PROCEDURE U_PERSONA
    @ID INT
   ,@NOMBRE VARCHAR(128)
   ,@APELLIDO VARCHAR(128)
   ,@DNI VARCHAR(32)
   ,@FNACTO DATETIME
   ,@GENERO CHAR(1)
   ,@DOMICILIO VARCHAR(1024)
AS
BEGIN
  BEGIN TRY
    UPDATE PERSONA SET
    NOMBRE = ISNULL(@NOMBRE, NOMBRE)
   ,APELLIDO = ISNULL(@APELLIDO, APELLIDO)
   ,DNI = ISNULL(@DNI, DNI)
   ,FNACTO = ISNULL(@FNACTO, FNACTO)
   ,GENERO = ISNULL(@GENERO, GENERO)
   ,DOMICILIO = ISNULL(@DOMICILIO, DOMICILIO)
    WHERE ID = ID
  END TRY
  BEGIN CATCH
     EXECUTE GetErrorInfo_sp
  END CATCH
END
GO
