DELIMITER //

DROP PROCEDURE IF EXISTS gendelete;

CREATE PROCEDURE gendelete(IN tab VARCHAR(128))
BEGIN
	DECLARE colname VARCHAR(512);
	DECLARE datatype VARCHAR(512);
	DECLARE ispk INTEGER;
	DECLARE pkname VARCHAR(64);
	DECLARE finished INTEGER DEFAULT 0;
	DECLARE c_col CURSOR FOR
	SELECT 
		COLUMN_NAME,
		CASE
			WHEN UPPER(DATA_TYPE) = 'VARCHAR' THEN CONCAT('VARCHAR(',CHARACTER_MAXIMUM_LENGTH,')')
			WHEN UPPER(DATA_TYPE) = 'CHAR' THEN CONCAT('CHAR(',CHARACTER_MAXIMUM_LENGTH,')')
			ELSE UPPER(DATA_TYPE)
		END as datatype,
		CASE WHEN COLUMN_KEY = 'PRI' THEN 1 ELSE 0 END as ispk
	FROM information_schema.columns
	WHERE table_name = tab
	  AND table_schema = 'UTN'
	ORDER BY ORDINAL_POSITION asc;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET finished = 1;
	
	CREATE TEMPORARY TABLE IF NOT EXISTS TTAB(fila VARCHAR(2048));
	TRUNCATE TABLE TTAB;
	
	INSERT INTO TTAB(fila) VALUES ('DELIMITER //');
	INSERT INTO TTAB(fila) VALUES (CONCAT('DROP PROCEDURE IF EXISTS D_',UPPER(tab),';'));
	INSERT INTO TTAB(fila) VALUES (CONCAT('CREATE PROCEDURE D_',UPPER(tab),'('));
	
	OPEN c_col;
	
	getcol: LOOP
		FETCH c_col INTO colname, datatype, ispk;
		IF ispk = 1 THEN
			INSERT INTO TTAB(fila) VALUES (CONCAT('IN ', colname, ' ', datatype));
			SET pkname = colname;
		END IF;
		IF finished = 1 THEN
			LEAVE getcol;
		END IF;
	END LOOP getcol;
	CLOSE c_col;

	INSERT INTO TTAB(fila) VALUES (')');
	INSERT INTO TTAB(fila) VALUES ('BEGIN');
	INSERT INTO TTAB(fila) VALUES (CONCAT('    DELETE FROM ', tab, ' WHERE ', pkname , ' = ', pkname, ';'));
	INSERT INTO TTAB(fila) VALUES ('END;');
	INSERT INTO TTAB(fila) VALUES ('//');
	INSERT INTO TTAB(fila) VALUES ('DELIMITER ;');

	SELECT fila FROM TTAB;

END;
//
DELIMITER ;
